QE_PARAMETERS = {
    "control": {
        "restart_mode": {"quote": True, "desc": "### restart_mode\n\nTells QE whether to start fresh or continue from a crash.\n\nSet to `'from_scratch'` (default) for a new run, or `'restart'` to resume an interrupted calculation using saved `outdir` files.\n\n- `'from_scratch'` : Start a brand new calculation (Default).\n- `'restart'` : Resume from a crashed or paused calculation."},
        "tstress": {"quote": False, "desc": "### tstress\n\nCalculates how much the crystal is being squeezed.\n\nSet to `.true.` to compute the macroscopic stress tensor. Automatically enabled during `vc-relax`.\n\n- `.false.` : Do not calculate stress (Default).\n- `.true.` : Calculate and print the 3x3 stress tensor."},
        "tprnfor": {"quote": False, "desc": "### tprnfor\n\nCalculates the forces pushing or pulling on each atom.\n\nSet to `.true.` to print atomic forces in the output file. Automatically enabled during `relax` and `vc-relax`.\n\n- `.false.` : Do not print forces (Default).\n- `.true.` : Calculate and print the force vector for every atom."},
        "disk_io": {"quote": True, "desc": "### disk_io\n\nControls how much data QE writes to your hard drive.\n\nSetting to `'low'` can speed up calculations by reducing read/write overhead on clusters.\n\n- `'high'` : Save everything (Default for some versions). Huge files.\n- `'low'` : Only save essential data to continue the run. Best for performance.\n- `'none'` : Save absolutely nothing. (Not recommended if you need DOS/Bands later)."},
        "verbosity": {"quote": True, "desc": "### verbosity\n\nControls how talkative QE is in its output file.\n\nHigh verbosity prints extra details like band energies at every single k-point and forces.\n\n- `'low'` : Keep output clean and minimal (Default).\n- `'high'` : Print extensive details (Great for debugging or extracting band data)."},
        "max_seconds": {"quote": False, "desc": "### max_seconds\n\nA time limit for your calculation.\n\nQE will cleanly stop and save its progress if the run time exceeds this value (in seconds). Extremely useful for HPC cluster queues.\n\n- Example: `max_seconds = 86000` (Stops cleanly before a 24-hour cluster limit)."},
    },
    "system": {
        "ecutrho": {"quote": False, "desc": "### ecutrho\n\nThe resolution of the electron cloud (charge density).\n\nKinetic energy cutoff (in Ry) for charge density and potential. If omitted, QE defaults it to `4 * ecutwfc`.\n\n- `4 * ecutwfc` : Ideal for Norm-Conserving pseudopotentials.\n- `8` to `12 * ecutwfc` : Required for Ultrasoft (USPP) or PAW pseudopotentials."},
        "nbnd": {"quote": False, "desc": "### nbnd\n\nThe number of electronic energy levels (bands) to compute.\n\nBy default, QE only calculates enough bands to fit all electrons. If you have a metal or need conduction bands for optical properties, you must increase this.\n\n- Example: `nbnd = 20`"},
        "tot_charge": {"quote": False, "desc": "### tot_charge\n\nThe net electrical charge of your entire simulation box.\n\nUsed to simulate charged defects or ions. QE compensates this by adding a uniform background charge of the opposite sign to keep the universe neutral.\n\n- `0.0` : Neutral system (Default).\n- `-1.0` : Adding one extra electron (Anion).\n- `+1.0` : Removing one electron (Cation)."},
        "tot_magnetization": {"quote": False, "desc": "### tot_magnetization\n\nForces the material to have a specific net magnetic moment.\n\nFixes the total majority spin minus minority spin. This is useful if you want to force the system into a specific magnetic state instead of letting it find it naturally.\n\n- `-1` : Unconstrained (Default). QE finds the best magnetic state itself.\n- `0.0` : Forces an anti-ferromagnetic or non-magnetic state.\n- `2.0` : Forces a net magnetic moment of 2 Bohr magnetons."},
        "nspin": {"quote": False, "desc": "### nspin\n\nTells QE whether to care about electron spin (magnetism).\n\nControls the spin polarization of the calculation. If your material is magnetic, you must change this.\n\n- `1` : Non-magnetic (Default). Fast, ignores spin differences.\n- `2` : Spin-polarized (collinear). For ferromagnets or anti-ferromagnets. (Requires `starting_magnetization`!).\n- `4` : Non-collinear magnetism / Spin-orbit coupling."},
        "starting_magnetization1": {"quote": False, "desc": "### starting_magnetization(i)\n\nThe initial 'kick' to start a magnetic calculation.\n\nProvides a starting guess for the magnetic moment of atomic species `i`. Without this kick, a spin-polarized calculation (`nspin=2`) might get stuck in a non-magnetic state.\n\n- `0.0` : Non-magnetic starting guess (Default).\n- `0.5` : A strong positive magnetic kick (Spin Up).\n- `-0.5` : A strong negative magnetic kick (Spin Down)."},
        "occupations": {"quote": True, "desc": "### occupations\n\nHow electrons are distributed across the energy levels.\n\nCrucial for metals where the Fermi level cuts through a band. For insulators, a fixed distribution is enough.\n\n- `'fixed'` : Default for insulators. Electrons perfectly fill the lowest bands.\n- `'smearing'` : Required for metals! Blurs the Fermi level to help convergence.\n- `'tetrahedra'` : For highly accurate Density of States (DOS) calculations."},
        "smearing": {"quote": True, "desc": "### smearing\n\nThe mathematical shape used to blur the Fermi level.\n\nOnly active if `occupations = 'smearing'`. Different shapes have different numerical advantages.\n\n- `'gauss'` : Simple Gaussian blur. Standard but not the most accurate.\n- `'m-p'` : Methfessel-Paxton. Best for metals, gives accurate forces.\n- `'m-v'` : Marzari-Vanderbilt (Cold). Great for metals, avoids negative occupancies.\n- `'f-d'` : Fermi-Dirac. Physically represents temperature smearing."},
        "degauss": {"quote": False, "desc": "### degauss\n\nThe 'width' of the smearing blur.\n\nThe smearing parameter (in Ry). A larger value helps difficult metals converge faster, but makes the physics less realistic. Must be checked for convergence.\n\n- Example: `degauss = 0.01` to `0.02` (Typical safe values)."},
        "vdw_corr": {"quote": True, "desc": "### vdw_corr\n\nAdds the weak 'sticky' forces between molecules or layers.\n\nStandard DFT ignores van der Waals dispersion forces. If your material has layered structures (like Graphite) or molecules, you must turn this on.\n\n- `'dft-d'` : Grimme's DFT-D2. Simple and widely used.\n- `'dft-d3'` : Grimme's DFT-D3. More accurate and modern.\n- `'ts-vdw'` : Tkatchenko-Scheffler method."},
        "assume_isolated": {"quote": True, "desc": "### assume_isolated\n\nStops the material from interacting with its own infinite clones.\n\nQE assumes your box repeats infinitely in all directions. If you are simulating a 2D sheet or a 0D molecule, you must stop the layers from interacting via vacuum.\n\n- `'none'` : Fully periodic 3D crystal (Default).\n- `'2D'` : Cuts off interactions in the Z-direction for flat sheets.\n- `'m-t'` : Makov-Payne correction for 0D molecules."},
        "nosym": {"quote": False, "desc": "### nosym\n\nForces QE to forget about crystal symmetry.\n\nNormally, QE uses symmetry to skip redundant calculations and save huge amounts of time.\n\n- `.false.` : Use symmetry (Default and highly recommended).\n- `.true.` : Completely disable symmetry. Very slow, but sometimes needed if symmetry breaks your specific defect calculation."},
        "noinv": {"quote": False, "desc": "### noinv\n\nForces QE to forget about inversion symmetry.\n\n- `.false.` : Use inversion symmetry (Default).\n- `.true.` : Disable inversion symmetry. Useful if you want to calculate properties that require breaking inversion."},
        "lda_plus_u": {"quote": False, "desc": "### lda_plus_u\n\nTurns on the DFT+U correction for 'stubborn' electrons.\n\nStandard DFT fails for highly localized d- or f-orbital electrons (like in Transition Metal Oxides). DFT+U adds an energy penalty to fix this.\n\n- `.false.` : Standard DFT (Default).\n- `.true.` : Enable DFT+U. (Requires `Hubbard_U` parameters to be set!)."},
        "Hubbard_U1": {"quote": False, "desc": "### Hubbard_U(i)\n\nThe strength of the DFT+U penalty.\n\nThe effective U parameter (in eV) applied to atomic species `i`. You usually get this value from literature or linear response calculations.\n\n- Example: `Hubbard_U(1) = 4.5`"},
    },
    "electrons": {
        "mixing_beta": {"quote": False, "desc": "### mixing_beta\n\nThe speed limit of the SCF convergence.\n\nThe mixing factor for the self-consistency loop. A high value converges faster but can crash (oscillate). A low value is safer but takes more steps.\n\n- `0.7` : Default. Works well for simple semiconductors like Silicon.\n- `0.3` : Recommended if your metal (like Aluminum) refuses to converge."},
        "electron_maxstep": {"quote": False, "desc": "### electron_maxstep\n\nThe patience limit of the SCF loop.\n\nThe maximum number of iterations allowed before QE gives up. If your calculation hits this, it means your `mixing_beta` is too high or your system is very complex.\n\n- Example: `electron_maxstep = 100`"},
        "mixing_mode": {"quote": True, "desc": "### mixing_mode\n\nThe algorithm used to mix charge densities.\n\nDetermines how QE mixes the old and new charge densities in the iterative loop.\n\n- `'plain'` : Broyden mixing (Default).\n- `'TF'` : Thomas-Fermi mixing (Great for large metallic systems).\n- `'local-TF'` : Local TF (Great for highly inhomogeneous systems like surfaces)."},
        "diagonalization": {"quote": True, "desc": "### diagonalization\n\nThe math engine used to solve the Hamiltonian.\n\n- `'david'` : Davidson algorithm (Default). Fast and reliable.\n- `'cg'` : Conjugate Gradient. Slower, but extremely stable. Use this if 'david' keeps crashing."},
        "startingpot": {"quote": True, "desc": "### startingpot\n\nHow to guess the initial potential.\n\n- `'atomic'` : Start from a superposition of atomic potentials (Default).\n- `'file'` : Read the potential from an existing `outdir`. (Used when restarting)."},
        "startingwfc": {"quote": True, "desc": "### startingwfc\n\nHow to guess the initial wavefunctions.\n\n- `'atomic+random'` : Default. Atomic wavefunctions with a bit of randomness to break symmetries.\n- `'random'` : Fully random guess.\n- `'file'` : Read from an existing `outdir`."},
    },
    "ions": {
        "ion_dynamics": {"quote": True, "desc": "### ion_dynamics\n\nThe algorithm used to move the atoms.\n\n- `'bfgs'` : Default and highly recommended for relaxation.\n- `'damp'` : Damped molecular dynamics."},
    },
    "cell": {
        "cell_dynamics": {"quote": True, "desc": "### cell_dynamics\n\nThe algorithm used to change the box shape.\n\n- `'bfgs'` : Default and highly recommended for vc-relax.\n- `'damp'` : Damped molecular dynamics."},
        "press": {"quote": False, "desc": "### press\n\nThe target external pressure.\n\nTarget pressure (in kbar) for a variable-cell relaxation. If you want to compress the material, increase this.\n\n- Example: `press = 0.0` (Default, ambient pressure)."},
        "cell_dofree": {"quote": True, "desc": "### cell_dofree\n\nLocks certain dimensions of your box from changing.\n\nUseful if you want to optimize the cell but restrict it to remain 2D, or keep the volume constant.\n\n- `'all'` : Fully flexible box (Default).\n- `'volume'` : Keeps the total volume constant, only changes the shape.\n- `'2Dxy'` : Only allows the x and y axes to relax (Useful for 2D materials)."},
    }
}
