import copy
from textual.screen import Screen
from textual.app import ComposeResult
from textual.containers import Horizontal, Vertical, Center, VerticalScroll
from textual.widgets import Static, Input, OptionList, Button
from textual.widgets.option_list import Option
from textual.screen import ModalScreen
from textual.widget import Widget
from textual.reactive import reactive
from textual import events, on
from textual.geometry import Region
from rich.text import Text
from rich.markdown import Markdown
from qelearn.ui.parameters_db import QE_PARAMETERS

LEARNING_DATA_SETUP = {
    "control_block": "### &CONTROL\n\nThe control room of your calculation.\n\nThe `&CONTROL` namelist dictates the fundamental workflow of Quantum ESPRESSO, telling it what to calculate, where to save files, and how to manage runtime.",
    "calculation": "### calculation\n\nSets the main goal of your simulation.\n\nDefines the fundamental type of DFT calculation to perform.\n\n- `'scf'` : Self-Consistent Field. Finds the ground state energy and charge density. (Default)\n- `'nscf'` : Non-SCF. Uses existing charge density to calculate Band Structure or DOS.\n- `'relax'` : Geometry optimization. Moves atoms to minimize forces.\n- `'vc-relax'` : Variable-cell relaxation. Optimizes both atomic positions and cell shape.",
    "slash": "### End of Block\n\nThe `/` character indicates the end of a Fortran namelist block.",
    "empty": "### (Empty Line)\n\nJust an empty line for readability.",
    "system_block": "### &SYSTEM\n\nThe physical blueprint of your material.\n\nThe `&SYSTEM` namelist describes the core physics of the simulation, including the crystal lattice, the types of atoms, the electrons, and how fine the computational mesh should be.",
    "electrons_block": "### &ELECTRONS\n\nThe solver engine of your calculation.\n\nThe `&ELECTRONS` namelist contains the algorithms used to iteratively solve the Kohn-Sham equations until self-consistency is reached.",
    "ions_block": "### &IONS\n\nThe atomic movers.\n\nThe `&IONS` namelist contains parameters for ionic relaxation (moving atoms to minimize forces). Required when `calculation` is 'relax' or 'vc-relax'.",
    "cell_block": "### &CELL\n\nThe box shape optimizers.\n\nThe `&CELL` namelist contains parameters for cell volume/shape relaxation. Required when `calculation` is 'vc-relax'.",
    "atomic_species_block": "### ATOMIC_SPECIES\n\nThe roster of elements.\n\nDefines the atomic types, their masses, and the pseudopotential files used for them. You must have exactly `ntyp` rows here.",
    "atomic_positions_block": "### ATOMIC_POSITIONS\n\nThe exact locations of your atoms.\n\nDefines the atomic coordinates in the unit cell. You must have exactly `nat` rows here.",
    "kpoints_block": "### K_POINTS\n\nThe resolution of the Brillouin zone.\n\nDefines the 3D grid used to sample the reciprocal space. The word in brackets defines the generation method.\n\n- `{automatic}` : Generates a regular Monkhorst-Pack grid (Most common).\n- `{gamma}` : Only uses the Gamma point (Fastest, for molecules/isolates).\n- `{crystal}` : You manually list every k-point in fractional coordinates.",
    "prefix": "### prefix\n\nThe nickname for your material's files.\n\nUsed as the prefix for all output data files and folders generated by QE. Must match across multi-step calculations.\n\n- Example: `prefix = 'silicon'`",
    "outdir": "### outdir\n\nThe folder where QE dumps its heavy data.\n\nSpecifies the directory path to store temporary files like wavefunctions and charge densities. Can be absolute or relative.\n\n- Example: `outdir = './tmp/'`",
    "pseudo_dir": "### pseudo_dir\n\nThe library folder for your atomic potentials.\n\nSpecifies the directory path where QE will look for your `.UPF` pseudopotential files.\n\n- Example: `pseudo_dir = '../pseudo/'`",
    "ibrav": "### ibrav\n\nThe shape of your crystal's unit cell.\n\nDefines the Bravais lattice geometry. Based on this number, QE will know how to construct the simulation box.\n\n- `0` : Free cell. You must manually define the vectors in `CELL_PARAMETERS`. (Most flexible, highly recommended)\n- `1` : Simple Cubic (sc).\n- `2` : Face-Centered Cubic (fcc).\n- `3` : Body-Centered Cubic (bcc).\n- `4` : Hexagonal or Trigonal (P).\n- `...`: (See QE manual for others)",
    "celldm1": "### Cell Dimension 1\n\nThe lattice parameter `a` in Bohr.",
    "nat": "### nat (Number of Atoms)\n\nThe total population of atoms in your box.\n\nSpecifies the total number of atoms present in the unit cell. This number must exactly match the number of rows you write in the `ATOMIC_POSITIONS` block.\n\n- Example: `nat = 2` (For the 2-atom primitive cell of Silicon or Graphene)",
    "ntyp": "### ntyp (Number of Types)\n\nThe number of distinct elements in your material.\n\nSpecifies the variety of atomic species. This must exactly match the number of rows in the `ATOMIC_SPECIES` block.\n\n- Example: `ntyp = 1` (For a pure material like Silicon or Aluminum)",
    "ecutwfc": "### ecutwfc\n\nThe resolution or 'sharpness' of your electrons.\n\nKinetic energy cutoff (in Ry) for the wavefunctions. A higher value means a more accurate but slower calculation. Must be chosen based on a convergence test for your specific pseudopotential.\n\n- Example: `ecutwfc = 40.0` (A standard starting point for Norm-Conserving pseudopotentials)",
    "conv_thr": "### conv_thr\n\nThe target precision of the calculation.\n\nThe convergence threshold for energy in Ry. The SCF loop stops when the estimated energy error is less than this value.\n\n- Example: `conv_thr = 1.0d-8` (Standard for most SCF calculations)",
    "atomic_species": "### ATOMIC_SPECIES\n\nThe roster of elements.\n\nFormat: `Element Mass Pseudopotential_File`.\nThe mass is mostly used for molecular dynamics or phonons. The pseudopotential file must exist in your `pseudo_dir`.\n\n- Example: `Si 28.086 Si.pbe-n-kjpaw_psl.1.0.0.UPF`\n\n*Press `Enter` to add a new row. Press `Backspace` on an empty row to delete it.*",
    "cell_parameters_unit": "### CELL_PARAMETERS Unit\n\nDefines the mathematical scale for your lattice vectors.\n\n- `{angstrom}` : Vectors are directly in Angstroms (Highly recommended, matches VESTA).\n- `{alat}` : Vectors are scaled by `celldm(1)`.\n- `{bohr}` : Vectors are directly in Bohr radii.",
    "cell_parameters": "### CELL_PARAMETERS\n\nThe 3D shape of your box.\n\nA 3x3 matrix defining the three lattice vectors (v1, v2, v3) of your simulation cell.\n\n*Press `Enter` to add a new row. Press `Backspace` on an empty row to delete it.*",
    "atomic_positions_unit": "### ATOMIC_POSITIONS Unit\n\nDefines the coordinate system for your atoms.\n\n- `{crystal}` : Fractional coordinates (0.0 to 1.0). Highly recommended! If your box stretches, atoms move perfectly with it.\n- `{angstrom}` : Cartesian coordinates in Angstroms.\n- `{alat}` : Cartesian coordinates scaled by lattice parameter.",
    "atomic_positions": "### ATOMIC_POSITIONS\n\nThe exact locations of your atoms.\n\nFormat: `Element X Y Z`.\n\n- Example: `Si 0.2500000000 0.2500000000 0.2500000000`\n\n*Press `Enter` to add a new row. Press `Backspace` on an empty row to delete it.*\n*(Tip: You can easily paste coordinates from other files directly here!)*",
    "kpoints": "### K_POINTS\n\nThe resolution of the Brillouin zone.\n\nFormat: `nk1 nk2 nk3 sk1 sk2 sk3`.\nThe first three numbers are the grid size. The last three are the shift (0 or 1).\n\n- Example: `4 4 4 0 0 0` (A 4x4x4 grid with no shift)\n\n*Press `Enter` to add a new row. Press `Backspace` on an empty row to delete it.*"
}

for section, params in QE_PARAMETERS.items():
    for key, data in params.items():
        if key not in LEARNING_DATA_SETUP:
            LEARNING_DATA_SETUP[key] = data["desc"]

SCF_TEMPLATE = [
    {"type": "static", "key": "control_block", "text": "&CONTROL"},
    {"type": "static", "key": "calculation", "text": "  calculation = 'scf',"},
    {"type": "field", "key": "prefix", "label": "  prefix = ", "value": "", "quote": True, "suffix": ","},
    {"type": "field", "key": "outdir", "label": "  outdir = ", "value": "./out", "quote": True, "suffix": ","},
    {"type": "field", "key": "pseudo_dir", "label": "  pseudo_dir = ", "value": "../pseudo", "quote": True, "suffix": ","},
    {"type": "static", "key": "slash", "text": "/"},
    {"type": "static", "key": "empty", "text": ""},
    {"type": "static", "key": "system_block", "text": "&SYSTEM"},
    {"type": "field", "key": "ibrav", "label": "  ibrav = ", "value": "", "quote": False, "suffix": ","},
    {"type": "field", "key": "nat", "label": "  nat = ", "value": "", "quote": False, "suffix": ","},
    {"type": "field", "key": "ntyp", "label": "  ntyp = ", "value": "", "quote": False, "suffix": ","},
    {"type": "field", "key": "ecutwfc", "label": "  ecutwfc = ", "value": "40.0", "quote": False, "suffix": ","},
    {"type": "static", "key": "slash", "text": "/"},
    {"type": "static", "key": "empty", "text": ""},
    {"type": "static", "key": "electrons_block", "text": "&ELECTRONS"},
    {"type": "field", "key": "conv_thr", "label": "  conv_thr = ", "value": "1.0d-8", "quote": False, "suffix": ","},
    {"type": "static", "key": "slash", "text": "/"},
    {"type": "static", "key": "empty", "text": ""},
    {"type": "static", "key": "atomic_species_block", "text": "ATOMIC_SPECIES"},
    {"type": "field", "key": "atomic_species", "label": "  ", "value": "", "quote": False, "suffix": ""},
    {"type": "static", "key": "empty", "text": ""},
    {"type": "field", "key": "cell_parameters_unit", "label": "CELL_PARAMETERS ", "value": "{angstrom}", "quote": False, "suffix": ""},
    {"type": "field", "key": "cell_parameters", "label": "  ", "value": "", "quote": False, "suffix": ""},
    {"type": "static", "key": "empty", "text": ""},
    {"type": "field", "key": "atomic_positions_unit", "label": "ATOMIC_POSITIONS ", "value": "{crystal}", "quote": False, "suffix": ""},
    {"type": "field", "key": "atomic_positions", "label": "  ", "value": "", "quote": False, "suffix": ""},
    {"type": "static", "key": "empty", "text": ""},
    {"type": "static", "key": "kpoints_block", "text": "K_POINTS {automatic}"},
    {"type": "field", "key": "kpoints", "label": "  ", "value": "", "quote": False, "suffix": ""},
]

class QEditor(Widget, can_focus=True):
    """A custom widget that looks like a text editor but acts as a form."""
    
    focused_line_idx = reactive(0)
    cursor_pos = reactive(0)
    cursor_visible = reactive(True)
    
    class FieldFocused(events.Message):
        """Emitted when a new field is focused."""
        def __init__(self, key: str) -> None:
            self.key = key
            super().__init__()

    def __init__(self, template, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.template = copy.deepcopy(template)

    def on_mount(self) -> None:
        self.set_interval(0.5, self.toggle_cursor)
        
        # Auto-focus the first editable field
        for i, item in enumerate(self.template):
            if item.get("type") == "field":
                self.focused_line_idx = i
                val = item.get("value", "")
                self.cursor_pos = len(val) if "\n" not in val else len(val.split("\n")[-1])
                break
        
    def toggle_cursor(self) -> None:
        self.cursor_visible = not self.cursor_visible
                
    def get_content_height(self, container, viewport, width) -> int:
        total_lines = 0
        for item in self.template:
            if item.get("type") == "field":
                val = item.get("value", "")
                total_lines += val.count("\n") + 1
            else:
                total_lines += 1
        return total_lines

    def watch_focused_line_idx(self, old_idx: int, new_idx: int) -> None:
        if 0 <= new_idx < len(self.template):
            line = self.template[new_idx]
            if line.get("type") == "field":
                self.cursor_pos = len(line.get("value", ""))
            self.post_message(self.FieldFocused(line.get("key", "empty")))
        
        # Manually force the parent VerticalScroll to scroll with a margin
        if getattr(self, "parent", None) and hasattr(self.parent, "scroll_y"):
            scroll_y = self.parent.scroll_y
            viewport_height = self.parent.size.height
            margin = 5
            
            target_y = scroll_y
            if new_idx < scroll_y + margin:
                target_y = max(0, new_idx - margin)
            elif new_idx > scroll_y + viewport_height - 1 - margin:
                target_y = new_idx - viewport_height + 1 + margin
                
            if target_y != scroll_y:
                self.parent.scroll_to(y=target_y, animate=False)

    def render(self) -> Text:
        lines = []
        for i, line in enumerate(self.template):
            line_num = f"{i+1:3d} "
            
            if line["type"] == "static":
                text_content = Text(line["text"])
            else:
                label = line["label"]
                val = line["value"]
                suffix = line.get("suffix", "")
                
                if i == self.focused_line_idx:
                    if self.cursor_visible:
                        if self.cursor_pos < len(val):
                            val_styled = Text(val[:self.cursor_pos]) + Text(val[self.cursor_pos], style="reverse") + Text(val[self.cursor_pos+1:])
                        else:
                            val_styled = Text(val) + Text(" ", style="reverse")
                    else:
                        val_styled = Text(val)
                    
                    if line.get("quote"):
                        text_content = Text(label) + Text("'") + val_styled + Text("'") + Text(suffix)
                    else:
                        text_content = Text(label) + val_styled + Text(suffix)
                else:
                    if val == "":
                        val_str = "''" if line.get("quote") else ""
                    else:
                        val_str = f"'{val}'" if line.get("quote") else val
                    text_content = Text(label) + Text(val_str, style="red bold") + Text(suffix)
                
            if i == self.focused_line_idx:
                text_content.stylize("black on white")
                
            styled_line = Text(line_num, style="dim") + text_content
            lines.append(styled_line)
            
        return Text("\n").join(lines)

    def on_key(self, event: events.Key) -> None:
        if event.key == "up":
            event.stop()
            event.prevent_default()
            if self.focused_line_idx > 0:
                self.focused_line_idx -= 1
        elif event.key == "down":
            event.stop()
            event.prevent_default()
            if self.focused_line_idx < len(self.template) - 1:
                self.focused_line_idx += 1
        elif event.key == "left":
            event.stop()
            event.prevent_default()
            line = self.template[self.focused_line_idx]
            if line.get("type") == "field" and self.cursor_pos > 0:
                self.cursor_pos -= 1
                self.cursor_visible = True
        elif event.key == "right":
            event.stop()
            event.prevent_default()
            line = self.template[self.focused_line_idx]
            if line.get("type") == "field" and self.cursor_pos < len(line.get("value", "")):
                self.cursor_pos += 1
                self.cursor_visible = True
        elif event.key == "enter":
            event.stop()
            event.prevent_default()
            line = self.template[self.focused_line_idx]
            if line.get("key") in ("atomic_positions", "atomic_species", "cell_parameters", "kpoints"):
                new_line = line.copy()
                if "value" in new_line:
                    new_line["value"] = ""
                self.template.insert(self.focused_line_idx + 1, new_line)
                self.focused_line_idx += 1
                self.cursor_pos = 0
                self.refresh(layout=True)
            else:
                if self.focused_line_idx < len(self.template) - 1:
                    self.focused_line_idx += 1
        elif event.key == "backspace":
            line = self.template[self.focused_line_idx]
            if line["type"] == "field":
                if self.cursor_pos > 0:
                    val = line["value"]
                    line["value"] = val[:self.cursor_pos - 1] + val[self.cursor_pos:]
                    self.cursor_pos -= 1
                    self.cursor_visible = True
                    self.refresh()
                elif line.get("key") in ("atomic_positions", "atomic_species", "cell_parameters", "kpoints") and sum(1 for l in self.template if l.get("key") == line.get("key")) > 1:
                    idx = self.focused_line_idx - 1
                    del self.template[self.focused_line_idx]
                    if idx >= 0:
                        self.focused_line_idx = idx
                    self.refresh(layout=True)
        elif event.key == "delete":
            line = self.template[self.focused_line_idx]
            if line["type"] == "field":
                val = line["value"]
                if self.cursor_pos < len(val):
                    line["value"] = val[:self.cursor_pos] + val[self.cursor_pos + 1:]
                    self.cursor_visible = True
                    self.refresh()
        elif event.key == "ctrl+a":
            event.stop()
            event.prevent_default()
            
            block = None
            for i in range(self.focused_line_idx, -1, -1):
                line = self.template[i]
                if line.get("type") == "static":
                    text = line.get("text", "")
                    if text.strip() == "/" and i != self.focused_line_idx:
                        break
                    elif text.startswith("&"):
                        if "&CONTROL" in text: block = "control"
                        elif "&SYSTEM" in text: block = "system"
                        elif "&ELECTRONS" in text: block = "electrons"
                        elif "&IONS" in text: block = "ions"
                        elif "&CELL" in text: block = "cell"
                        break
            
            if block:
                existing_keys = {line.get("key") for line in self.template}
                available_params = {k: v for k, v in QE_PARAMETERS[block].items() if k not in existing_keys}
                
                if available_params:
                    def insert_param(param_key: str):
                        if param_key:
                            quote = QE_PARAMETERS[block][param_key]["quote"]
                            new_line = {
                                "type": "field", 
                                "key": param_key, 
                                "label": f"  {param_key} = ", 
                                "value": "", 
                                "quote": quote, 
                                "suffix": ","
                            }
                            insert_idx = self.focused_line_idx
                            if self.template[self.focused_line_idx].get("text", "").strip() != "/":
                                insert_idx += 1
                                
                            self.template.insert(insert_idx, new_line)
                            self.focused_line_idx = insert_idx
                            self.cursor_pos = 0
                            self.refresh(layout=True)
                    
                    self.app.push_screen(AddParameterModal(available_params, block.upper()), insert_param)
        elif event.key == "ctrl+d":
            event.stop()
            event.prevent_default()
            line = self.template[self.focused_line_idx]
            if line.get("type") == "field" and line.get("key") not in ("atomic_positions", "atomic_species", "cell_parameters", "atomic_positions_unit", "cell_parameters_unit", "prefix", "outdir", "pseudo_dir", "ibrav", "nat", "ntyp", "ecutwfc", "kpoints"):
                del self.template[self.focused_line_idx]
                if self.focused_line_idx >= len(self.template):
                    self.focused_line_idx -= 1
                self.refresh(layout=True)
        elif event.key == "ctrl+n":
            workflow = getattr(self.app, 'workflow', 'scf')
            step = getattr(self.screen, 'step', 1)
            if workflow in ["band", "dos"] and step < 3:
                event.stop()
                event.prevent_default()
                if hasattr(self.screen, "action_next_step"):
                    self.screen.action_next_step()
        elif event.key == "ctrl+s":
            workflow = getattr(self.app, 'workflow', 'scf')
            step = getattr(self.screen, 'step', 1)
            if workflow in ["band", "dos"] and step < 3:
                event.stop()
                event.prevent_default()
                self.app.notify("Press [Ctrl+N] to proceed. Saving is done at the final step.", title="Workflow Incomplete", severity="warning")
                return
                
            event.stop()
            event.prevent_default()
            
            def save_file(filepath: str):
                if not filepath:
                    return
                import os
                
                def build_content(t):
                    lines = []
                    for item in t:
                        if item["type"] == "static":
                            lines.append(item.get("text", ""))
                        elif item["type"] == "field":
                            val = item.get("value", "").strip()
                            if val:
                                if item.get("key") in ("atomic_positions", "cell_parameters", "atomic_species", "kpoints") or "\n" in val:
                                    label = item.get("label", "")
                                    # apply label (indentation) to every line in multiline values
                                    indented_val = "\n".join(f"{label}{v}" for v in val.split("\n"))
                                    lines.append(indented_val)
                                else:
                                    quote = item.get("quote", False)
                                    label = item.get("label", "")
                                    suffix = item.get("suffix", "")
                                    if quote:
                                        lines.append(f"{label}'{val}'{suffix}")
                                    else:
                                        lines.append(f"{label}{val}{suffix}")
                    return "\n".join(lines) + "\n"
                
                try:
                    directory = os.path.dirname(filepath)
                    if directory:
                        os.makedirs(directory, exist_ok=True)
                        
                    workflow = getattr(self.app, 'workflow', 'scf')
                    step = getattr(self.screen, 'step', 1)
                    
                    if step == 3 and workflow in ["band", "dos"]:
                        # Save 3 files in the target directory (filepath is ignored or used as directory)
                        # Actually if filepath is 'project/bands/scf.in', we should put them in 'project/bands'
                        # Or if they type 'silicon', we put them in 'silicon/scf.in' etc.
                        # It's safest to just treat 'filepath' as the directory path in this case, or use its dirname if it has an extension.
                        target_dir = filepath if not filepath.endswith(".in") else os.path.dirname(filepath)
                        if not target_dir: target_dir = "."
                        os.makedirs(target_dir, exist_ok=True)
                        
                        scf_content = build_content(self.screen.workflow_data["scf_template"])
                        nscf_content = build_content(self.screen.workflow_data["nscf_template"])
                        post_content = build_content(self.template)
                        
                        with open(os.path.join(target_dir, "scf.in"), "w") as f: f.write(scf_content)
                        if workflow == "band":
                            with open(os.path.join(target_dir, "nscfbands.in"), "w") as f: f.write(nscf_content)
                            with open(os.path.join(target_dir, "bands.in"), "w") as f: f.write(post_content)
                        else:
                            with open(os.path.join(target_dir, "nscf.in"), "w") as f: f.write(nscf_content)
                            with open(os.path.join(target_dir, "dos.in"), "w") as f: f.write(post_content)
                            
                        self.app.notify("Successfully saved 3 files to current folder", title="Success", severity="information")
                    else:
                        with open(filepath, "w") as f:
                            f.write(build_content(self.template))
                        self.app.notify(f"Successfully saved {filepath} to current folder", title="Success", severity="information")
                except Exception as e:
                    self.app.notify(f"Failed to save: {str(e)}", title="Error", severity="error")
                    
            step = getattr(self.screen, 'step', 1)
            workflow = getattr(self.app, 'workflow', 'scf')
            
            if step == 1:
                default_name = "relax.in" if workflow == "relax" else "scf.in"
            elif step == 2:
                default_name = "nscf.in"
            else:
                default_name = "."
                
            save_file(default_name)
        elif event.is_printable:
            line = self.template[self.focused_line_idx]
            if line["type"] == "field":
                event.stop()
                event.prevent_default()
                val = line["value"]
                line["value"] = val[:self.cursor_pos] + event.character + val[self.cursor_pos:]
                self.cursor_pos += 1
                self.cursor_visible = True
                self.refresh()

    def on_paste(self, event: events.Paste) -> None:
        line = self.template[self.focused_line_idx]
        if line["type"] == "field":
            text = event.text.replace("\r", "")
            lines = text.split("\n")
            if line["key"] in ("atomic_positions", "atomic_species", "cell_parameters", "kpoints") and len(lines) > 1:
                val = line["value"]
                line["value"] = val[:self.cursor_pos] + lines[0] + val[self.cursor_pos:]
                for i, text_line in enumerate(lines[1:]):
                    if text_line.strip():
                        new_line = line.copy()
                        new_line["value"] = text_line
                        self.template.insert(self.focused_line_idx + i + 1, new_line)
                self.focused_line_idx += len([l for l in lines[1:] if l.strip()])
                self.cursor_pos = len(self.template[self.focused_line_idx]["value"])
            else:
                text_to_paste = text.replace("\n", " ")
                val = line["value"]
                line["value"] = val[:self.cursor_pos] + text_to_paste + val[self.cursor_pos:]
                self.cursor_pos += len(text_to_paste)
            self.refresh(layout=True)

class SearchInput(Input):
    def on_key(self, event: events.Key) -> None:
        if event.key == "down":
            self.screen.query_one(OptionList).focus()
            event.stop()

class ParamOptionList(OptionList):
    def on_key(self, event: events.Key) -> None:
        if event.key == "up" and self.highlighted == 0:
            self.screen.query_one(Input).focus()
            event.stop()

class AddParameterModal(ModalScreen[str]):
    """Modal screen for adding a QE parameter."""
    
    CSS = """
    AddParameterModal {
        align: center middle;
        background: rgba(0, 0, 0, 0.8);
    }
    #param-dialog {
        width: 60;
        height: 20;
        border: round #ffffff;
        background: #000000;
        padding: 1 2;
    }
    #param-search {
        margin-bottom: 1;
    }
    #param-list {
        height: 1fr;
    }
    """
    
    def __init__(self, parameters, block_name, **kwargs):
        super().__init__(**kwargs)
        self.parameters = parameters # dict of {key: data}
        self.block_name = block_name
        
    def compose(self) -> ComposeResult:
        with Vertical(id="param-dialog"):
            yield Static(f" ADD PARAMETER TO {self.block_name} ", classes="title")
            yield SearchInput(placeholder="Search parameters...", id="param-search")
            yield ParamOptionList(id="param-list")
            
    def on_mount(self) -> None:
        self.update_list("")
        self.query_one(Input).focus()
        
    def update_list(self, filter_text: str) -> None:
        opt_list = self.query_one(OptionList)
        opt_list.clear_options()
        for key in self.parameters:
            if filter_text.lower() in key.lower():
                opt_list.add_option(Option(key, id=key))
                
    def on_input_changed(self, event: Input.Changed) -> None:
        self.update_list(event.value)
        
    def on_option_list_option_selected(self, event: OptionList.OptionSelected) -> None:
        self.dismiss(event.option.id)
        
    def on_input_submitted(self, event: Input.Submitted) -> None:
        opt_list = self.query_one(OptionList)
        if opt_list.option_count > 0:
            self.dismiss(opt_list.get_option_at_index(0).id)

    BINDINGS = [
        ("escape", "cancel", "Cancel"),
        ("left", "focus_previous", "Previous"),
        ("right", "focus_next", "Next")
    ]
    
    def action_cancel(self) -> None:
        self.dismiss(None)

        
    def on_input_submitted(self, event: Input.Submitted) -> None:
        self.dismiss(event.value)

    BINDINGS = [
        ("escape", "cancel", "Cancel"),
        ("left", "focus_previous", "Previous"),
        ("right", "focus_next", "Next")
    ]
    
    def action_cancel(self) -> None:
        self.dismiss(None)

class SystemSetupScreen(Screen):
    """Screen for configuring the system parameters as a text editor."""
    
    def __init__(self, template=None, step=1, workflow_data=None, **kwargs):
        super().__init__(**kwargs)
        self.template = template if template is not None else copy.deepcopy(SCF_TEMPLATE)
        self.step = step
        self.workflow_data = workflow_data or {}
        self.empty_idx = 0
        self.easter_eggs = [
            "### (empty)\n\nA place for you to questioning your life purpose.",
            "### (empty)\n\nJust a void. Like your soul after 100 failed SCF iterations.",
            "### (empty)\n\nTake a deep breath. DFT is hard, but you're doing great.",
            "### (empty)\n\nThis space is intentionally left blank. Unlike your thesis."
        ]

    BINDINGS = [
        ("escape", "go_back", "Back")
    ]
    
    def action_go_back(self) -> None:
        try:
            current_template = self.query_one("QEditor").template
            if current_template != self.template:
                def check_confirm(confirm: bool):
                    if confirm:
                        if len(self.app.screen_stack) > 1:
                            self.app.pop_screen()
                        else:
                            from qelearn.main import QuitScreen
                            self.app.push_screen(QuitScreen())
                self.app.push_screen(ConfirmBackModal(), check_confirm)
                return
        except Exception:
            pass
            
        if len(self.app.screen_stack) > 1:
            self.app.pop_screen()
        else:
            from qelearn.main import QuitScreen
            self.app.push_screen(QuitScreen())

    CSS = """
    #setup-main {
        width: 90%;
        max-width: 160;
        height: 32;
        border: round #ffffff;
        padding: 0 1;
        background: #000000;
        margin-top: 2;
    }
    #hotkeys-bar {
        width: 90%;
        max-width: 160;
        text-align: center;
        color: #555555;
        margin-top: 1;
    }
    #config-panel {
        width: 50%;
        height: 100%;
        border-right: solid #ffffff;
        padding-right: 1;
    }
    #learn-panel {
        width: 50%;
        height: 100%;
        padding-left: 2;
    }
    QEditor {
        height: auto;
    }
    """

    def on_mount(self) -> None:
        self.query_one(QEditor).focus()

    def compose(self) -> ComposeResult:
        workflow = getattr(self.app, 'workflow', 'scf')
        hotkeys = "\\[↑/↓] Move   \\[←/→] Cursor   \\[ctrl+a] Add Param   \\[ctrl+d] Del Param   "
        if workflow in ["band", "dos"] and self.step < 3:
            hotkeys += "\\[ctrl+n] Next Step   \\[esc] Back"
        else:
            hotkeys += "\\[ctrl+s] Save All   \\[esc] Back" if workflow in ["band", "dos"] else "\\[ctrl+s] Save   \\[esc] Back"

        with Center():
            with Horizontal(id="setup-main"):
                with VerticalScroll(id="config-panel"):
                    yield QEditor(self.template, id="editor")

                with Vertical(id="learn-panel"):
                    title_text = " LEARN "
                    if workflow == "band":
                        title_text = " LEARN (Step 1: SCF)" if self.step == 1 else " LEARN (Step 2: NSCF Bands)" if self.step == 2 else " LEARN (Step 3: bands.in)"
                    elif workflow == "dos":
                        title_text = " LEARN (Step 1: SCF)" if self.step == 1 else " LEARN (Step 2: NSCF DOS)" if self.step == 2 else " LEARN (Step 3: dos.in)"
                        
                    yield Static(title_text, classes="title")
                    yield Static(Markdown(LEARNING_DATA_SETUP["control_block"]), id="setup-learn-content")
            yield Static(hotkeys, id="hotkeys-bar")

    @on(QEditor.FieldFocused)
    def update_learn_panel(self, event: QEditor.FieldFocused) -> None:
        """Update learn panel based on focused editor field."""
        if event.key == "empty":
            egg = self.easter_eggs[self.empty_idx]
            self.empty_idx = (self.empty_idx + 1) % len(self.easter_eggs)
            self.query_one("#setup-learn-content", Static).update(Markdown(egg))
        elif event.key in LEARNING_DATA_SETUP:
            self.query_one("#setup-learn-content", Static).update(Markdown(LEARNING_DATA_SETUP[event.key]))
        else:
            self.query_one("#setup-learn-content", Static).update(Markdown("### " + event.key + "\n\nDocumentation not available yet."))

    def action_next_step(self):
        workflow = getattr(self.app, 'workflow', 'scf')
        if workflow in ["band", "dos"]:
            # Retrieve the latest modified template from QEditor!
            current_template = self.query_one("QEditor").template
            
            if self.step == 1:
                # Step 1 to Step 2 (SCF to NSCF)
                import copy
                nscf_template = []
                
                # Lock fields except specific ones
                allowed_fields = ["kpoints", "nbnd", "occupations", "smearing", "degauss", "nosym", "verbosity"]
                for line_orig in current_template:
                    line = copy.deepcopy(line_orig)
                    
                    if line.get("key") == "calculation":
                        if line.get("type") == "static":
                            val = "bands" if workflow == "band" else "nscf"
                            line["text"] = f"  calculation = '{val}',"
                        else:
                            line["value"] = "bands" if workflow == "band" else "nscf"
                    elif line.get("key") == "kpoints_block":
                        line["text"] = "K_POINTS {crystal_b}" if workflow == "band" else "K_POINTS {automatic}"
                    elif line.get("key") == "kpoints":
                        if workflow == "band":
                            kpts = [
                                "4", 
                                "0.0000000000 0.0000000000 0.0000000000 20 ! Gamma", 
                                "0.5000000000 0.5000000000 0.0000000000 20 ! M", 
                                "0.3333333333 0.3333333333 0.0000000000 20 ! K", 
                                "0.0000000000 0.0000000000 0.0000000000 20 ! Gamma"
                            ]
                            line["value"] = kpts[0]
                            nscf_template.append(line)
                            for k in kpts[1:]:
                                new_kline = copy.deepcopy(line)
                                new_kline["value"] = k
                                nscf_template.append(new_kline)
                            continue # Already appended!
                        else:
                            line["value"] = "8 8 8 0 0 0"
                    
                    if line.get("type") == "field" and line.get("key") not in allowed_fields:
                        val = str(line.get("value", "")).strip()
                        if not val:
                            continue # Ignore empty fields to prevent broken static text
                            
                        val_str = ""
                        if line.get("quote"):
                            val_str = f"{line.get('label')}'{line.get('value')}'{line.get('suffix','')}"
                        else:
                            val_str = f"{line.get('label')}{line.get('value')}{line.get('suffix','')}"
                        
                        line["type"] = "static"
                        line["text"] = val_str
                    
                    nscf_template.append(line)
                
                workflow_data = {"scf_template": current_template}
                self.app.push_screen(SystemSetupScreen(template=nscf_template, step=2, workflow_data=workflow_data))
                
            elif self.step == 2:
                # Step 2 to Step 3 (NSCF to Post-processing Preview)
                prefix_val = "silicon"
                outdir_val = "./tmp"
                
                for line in current_template:
                    if line.get("key") == "prefix":
                        if line.get("type") != "static":
                            prefix_val = line.get("value", prefix_val)
                        else:
                            import re
                            m = re.search(r"'(.*?)'", line.get("text", ""))
                            if m: prefix_val = m.group(1)
                    elif line.get("key") == "outdir":
                        if line.get("type") != "static":
                            outdir_val = line.get("value", outdir_val)
                        else:
                            import re
                            m = re.search(r"'(.*?)'", line.get("text", ""))
                            if m: outdir_val = m.group(1)
                        
                if workflow == "band":
                    post_template = [
                        {"type": "static", "key": "bands_block", "text": "&BANDS"},
                        {"type": "static", "key": "prefix", "text": f"  prefix = '{prefix_val}',"},
                        {"type": "static", "key": "outdir", "text": f"  outdir = '{outdir_val}',"},
                        {"type": "static", "key": "filband", "text": "  filband = 'bands.dat',"},
                        {"type": "static", "key": "slash", "text": "/"}
                    ]
                else: # dos
                    post_template = [
                        {"type": "static", "key": "dos_block", "text": "&DOS"},
                        {"type": "static", "key": "prefix", "text": f"  prefix = '{prefix_val}',"},
                        {"type": "static", "key": "outdir", "text": f"  outdir = '{outdir_val}',"},
                        {"type": "static", "key": "fildos", "text": "  fildos = 'dos.dat',"},
                        {"type": "static", "key": "slash", "text": "/"}
                    ]
                
                workflow_data = self.workflow_data.copy()
                workflow_data["nscf_template"] = current_template
                self.app.push_screen(SystemSetupScreen(template=post_template, step=3, workflow_data=workflow_data))

class ConfirmBackModal(ModalScreen[bool]):
    """Screen that confirms going back with unsaved changes."""
    
    CSS = """
    ConfirmBackModal {
        align: center middle;
        background: rgba(0, 0, 0, 0.8);
    }
    #confirm-dialog {
        grid-size: 2;
        grid-gutter: 1 2;
        grid-rows: 1fr 3;
        padding: 0 1;
        width: 60;
        height: 11;
        border: round #ffffff;
        background: #000000;
    }
    #confirm-question {
        column-span: 2;
        height: 1fr;
        width: 1fr;
        content-align: center middle;
        color: #ffffff;
    }
    Button {
        width: 100%;
        background: #000000;
        color: #ffffff;
        border: solid #ffffff;
    }
    Button:hover {
        background: #ffffff;
        color: #000000;
    }
    Button#yes {
        color: #cc0000;
    }
    Button#yes:hover {
        color: #ff0000;
    }
    """

    def compose(self) -> ComposeResult:
        from textual.containers import Grid
        yield Grid(
            Static("You have unsaved changes.\nAre you sure you want to go back? Changes will be lost.", id="confirm-question"),
            Button("Yes, go back", id="yes"),
            Button("Cancel", id="cancel"),
            id="confirm-dialog"
        )

    def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "yes":
            self.dismiss(True)
        else:
            self.dismiss(False)
            
    BINDINGS = [
        ("escape", "cancel", "Cancel"),
        ("left", "focus_previous", "Previous"),
        ("right", "focus_next", "Next")
    ]
    
    def action_cancel(self) -> None:
        self.dismiss(False)

    def on_key(self, event) -> None:
        if event.key == "right":
            self.focus_next()
        elif event.key == "left":
            self.focus_previous()